app = "feline-matrix"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8008
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/_matrix/client/versions"

[[services]]
  internal_port = 8448
  protocol = "tcp"

  [[services.ports]]
    port = 8448
    handlers = ["tls"]

[mounts]
  source = "dendrite_data"
  destination = "/data"
