[global]
server_name = "ohana-matrix.xyz"
database_path = "/var/lib/conduwuit"
port = 6167
address = "0.0.0.0"
allow_registration = true
registration_token = "override-via-env"
allow_federation = true
trusted_servers = ["matrix.org"]
max_request_size = 20000000
